version: '3.8'

services:
  backend:
    build: ./STORM_Backend
    container_name: storm_backend
    networks:
      - stormnet
    expose:
      - "50051"

  envoy:
    image: envoyproxy/envoy:v1.26.1
    container_name: storm_envoy
    volumes:
      - ./STORM_Backend/envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - stormnet

  frontend:
    build:
      context: ./STORM_Frontend
    container_name: storm_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - envoy
    networks:
      - stormnet

networks:
  stormnet:
    driver: bridge
